# Generated by Django 5.0.7 on 2024-12-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashed_token', models.TextField()),
                ('token_type', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('sent_to', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('hashed_password', models.TextField(blank=True, null=True)),
                ('role', models.CharField(default='USER', max_length=50)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('preferred_locale', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_house_number', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAccessLog',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prisma_app.token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisma_app.user'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('hashed_session_token', models.TextField(blank=True, null=True)),
                ('anti_csrf_token', models.TextField(blank=True, null=True)),
                ('public_data', models.TextField(blank=True, null=True)),
                ('private_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prisma_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='organisations', to='prisma_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('new_report_available', models.CharField(default='Email', max_length=50)),
                ('new_sample_event', models.CharField(default='Email', max_length=50)),
                ('subject_file_upload', models.CharField(default='Email', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prisma_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SamplePickupRequested', 'Sample Pickup Requested'), ('SubjectSubmitted', 'Subject Submitted'), ('CegatSampleRegistrationRequest', 'Cegat Sample Registration Request'), ('SampleBillingChanged', 'Sample Billing Changed'), ('SamplingMethodChanged', 'Sampling Method Changed'), ('SamplePurposeChanged', 'Sample Purpose Changed'), ('SampleTestTypeChanged', 'Sample Test Type Changed'), ('SampleWetLabChanged', 'Sample Wet Lab Changed')], max_length=255)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prisma_app.user')),
            ],
        ),
    ]
