# Generated by Django 5.0.7 on 2024-12-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisma_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('test_type', models.CharField(choices=[('WholeGenomeSequencing', 'Whole Genome Sequencing'), ('WholeExomeSequencing', 'Whole Exome Sequencing'), ('SangerOnHold', 'Sanger On Hold')], default='SangerOnHold', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeUnit',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.TextField()),
                ('address_house_number', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_city', models.CharField(max_length=255)),
                ('address_post_code', models.CharField(max_length=20)),
                ('address_country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_units', to='prisma_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('myLifeHeart', 'My Life Heart'), ('myLifeGenome', 'My Life Genome'), ('myLifeCancer', 'My Life Cancer'), ('myLifeExome', 'My Life Exome'), ('sangerSequencing', 'Sanger Sequencing'), ('sangerOnHold', 'Sanger On Hold'), ('researchWES', 'Research WES'), ('researchWGS', 'Research WGS')], max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='prisma_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('arcensus_order_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='prisma_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('test_type', models.CharField(choices=[('WholeGenomeSequencing', 'Whole Genome Sequencing'), ('WholeExomeSequencing', 'Whole Exome Sequencing'), ('SangerOnHold', 'Sanger On Hold')], max_length=50)),
                ('test_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_settings', to='prisma_app.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='prisma_app.user')),
                ('samples', models.ManyToManyField(related_name='finance_settings', to='prisma_app.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.IntegerField(unique=True)),
                ('version_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Declared', 'Declared'), ('Submitted', 'Submitted')], default='Draft', max_length=50)),
                ('wizard_step', models.CharField(choices=[('PersonalInfo', 'Personal Info'), ('FamilyHistory', 'Family History'), ('ClinicalInfo', 'Clinical Info'), ('PhysicalInfo', 'Physical Info'), ('Summary', 'Summary'), ('Completed', 'Completed')], default='PersonalInfo', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prisma_app.officeunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='prisma_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='prisma_app.subject'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(blank=True, choices=[('Diagnostics', 'Diagnostics'), ('Update', 'Update'), ('Correction', 'Correction'), ('FailedAnalysis', 'Failed Analysis'), ('NegativeFollowUp', 'Negative Follow Up'), ('RawData', 'Raw Data'), ('DataAnalysis', 'Data Analysis'), ('Research', 'Research')], max_length=50, null=True)),
                ('test_type', models.CharField(blank=True, choices=[('WholeGenomeSequencing', 'Whole Genome Sequencing'), ('WholeExomeSequencing', 'Whole Exome Sequencing'), ('SangerOnHold', 'Sanger On Hold')], max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('JSON', 'JSON')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reports', to='prisma_app.order')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='prisma_app.user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prisma_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Failed', 'Failed'), ('OK', 'OK')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='prisma_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='prisma_app.subject'),
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('is_pedigree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prisma_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectShare',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('Read', 'Read'), ('ReadWrite', 'Read & Write')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='prisma_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_subjects', to='prisma_app.user')),
            ],
        ),
    ]
